version: '3.8'

volumes:
  trailerplan-data:
    driver: local
    driver_opts:
      type: none
      device: ./data/docker/app/
      o: bind

networks:
  trailerplan-network:
    driver: bridge

services:
  app_java:
    restart:  always
    image: ${APP_PROJECT}/${APP_SUB_PROJECT}:${APP_VERSION}
    hostname: ${APP_HOSTNAME}
    container_name: ${APP_CONTAINER_NAME}
    build:
      context: .
      dockerfile: data/container/app_java/${DOCKER_FILE}
    env_file:
      - ./data/container/config/${ENV_FILE}
    volumes:
      - trailerplan-data:/app/
    ports:
      - "8080:8080"
    command: /usr/local/openjdk-11/bin/java -jar /app/trailerplan-event-api.jar com.trailerplan.application.TrailerplanEventApiApp
    networks:
      - trailerplan-network