FROM openjdk:11.0.12-jre
MAINTAINER Buon SUI <boonsuli@gmail.com>
VOLUME /app
RUN mkdir -p /app/
WORKDIR /app
COPY ./target/trailerplan-event-api-1.0.0-SNAPSHOT.jar /app/trailerplan-event-api.jar
CMD ["/usr/local/openjdk-11/bin/java", "-Dspring.profiles.active=int", "-jar", "/app/trailerplan-event-api.jar"]
